name: fomo
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - einops>=0.7.0
  - tqdm>=4.65.0
  - pandas>=2.0.3
  - seaborn>=0.12.2
  - jupyter>=1.0.0
  - pytest>=7.4.0
  - pip:
      - perceiver-pytorch>=0.8.7
      - pytest-readme>=1.0.1
      - git+https://github.com/cybertronai/pytorch-lamb.git
